### model
model_name_or_path: google/gemma-2-2b-it
flash_attn: fa2
#attn_implementation: eager
### method
stage: rm
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json


### dataset
dataset: gsm8k_gemma2_264
template: gemma
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/gemma-2-2b-it/full/reward
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: linear
weight_decay: 0.0
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 2
