
script_type: quest.serving.vllm_server
args:
  model: "allenai/Llama-3.1-Tulu-3-8B-SFT"
  tensor_parallel_size: ${DEVICE_COUNT}
  gpu_memory_utilization: 0.95
  max_new_tokens: 1024
  max_prompt_length: 2048
  dtype: bfloat16
